-- Insert sample destinations
INSERT INTO destinations (id, name, country, description, image_url, rating, price_range, best_time, highlights, category) VALUES
('dest_1', 'Meghalaya', 'India', 'A lush, hilly state known for its living root bridges, waterfalls, and rolling green landscapes.', '/placeholder.svg?height=300&width=400&text=Meghalaya', 4.8, '$$$', 'April-June, September-October', '{"Living Root Bridges", "Cherrapunji", "Shillong", "Nohkalikai Falls"}', 'Nature'),
('dest_2', 'Tokyo', 'Japan', 'A bustling metropolis blending traditional culture with cutting-edge technology.', '/placeholder.svg?height=300&width=400&text=Tokyo', 4.7, '$$$$', 'March-May, September-November', '{"Shibuya Crossing", "Tokyo Tower", "Senso-ji Temple", "Tsukiji Fish Market"}', 'Urban'),
('dest_3', 'Ladakh', 'India', 'A high-altitude desert famous for its monasteries, mountain passes, and stunning Himalayan landscapes.', '/placeholder.svg?height=300&width=400&text=Ladakh', 4.6, '$$', 'May-September', '{"Pangong Lake", "Leh Palace", "Magnetic Hill", "Nubra Valley"}', 'Adventure'),
('dest_4', 'Mizoram', 'India', 'A picturesque state with rolling hills, vibrant tribal culture, and beautiful lakes.', '/placeholder.svg?height=300&width=400&text=Mizoram', 4.5, '$$', 'October-March', '{"Aizawl", "Vantawng Falls", "Reiek Tlang", "Palak Dil"}', 'Nature'),
('dest_5', 'Santorini', 'Greece', 'Stunning Greek island famous for its white-washed buildings, blue-domed churches, and sunsets.', '/placeholder.svg?height=300&width=400&text=Santorini', 4.9, '$$$', 'April-October', '{"Oia Village", "Red Beach", "Akrotiri", "Fira Town"}', 'Beach'),
('dest_6', 'Dubai', 'UAE', 'Modern city known for luxury shopping, ultramodern architecture, and vibrant nightlife.', '/placeholder.svg?height=300&width=400&text=Dubai', 4.4, '$$$$', 'November-March', '{"Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari"}', 'Luxury')
ON CONFLICT (id) DO NOTHING;

-- Insert sample hotels
INSERT INTO hotels (id, name, location, description, image_url, rating, price, original_price, category, amenities, features, availability) VALUES
('hotel_1', 'Ri Kynjai – Serenity by the Lake', 'Meghalaya, India', 'Luxury lakeside resort offering stunning views and warm Khasi hospitality.', '/placeholder.svg?height=300&width=400&text=Ri+Kynjai', 4.8, 220.00, 300.00, 'Luxury', '{"Spa", "Fine Dining", "Lake View", "Cultural Activities"}', '{"Umiam Lake View", "Traditional Architecture", "Nature Trails"}', true),
('hotel_2', 'Park Hyatt Tokyo', 'Tokyo, Japan', 'Sophisticated hotel in Shinjuku with panoramic city views.', '/placeholder.svg?height=300&width=400&text=Park+Hyatt+Tokyo', 4.7, 650.00, 800.00, 'Luxury', '{"Spa", "Pool", "Business Center", "Fitness Center"}', '{"City Views", "Traditional Japanese Design", "Premium Location"}', true),
('hotel_3', 'The Grand Dragon Ladakh', 'Ladakh, India', 'Upscale hotel blending Ladakhi tradition with modern comfort, offering breathtaking mountain views.', '/placeholder.svg?height=300&width=400&text=Grand+Dragon+Ladakh', 4.6, 180.00, 250.00, 'Resort', '{"Heating", "Restaurant", "Tour Desk", "Garden"}', '{"Mountain Views", "Traditional Decor", "Central Location"}', true),
('hotel_4', 'Hotel Regency', 'Mizoram, India', 'Comfortable hotel in Aizawl offering panoramic city views and modern amenities.', '/placeholder.svg?height=300&width=400&text=Hotel+Regency', 4.5, 90.00, 130.00, 'Boutique', '{"Restaurant", "Free Wi-Fi", "Room Service", "Parking"}', '{"City Views", "Central Location", "Budget Friendly"}', true),
('hotel_5', 'Canaves Oia Hotel', 'Santorini, Greece', 'Boutique hotel with infinity pools and caldera views.', '/placeholder.svg?height=300&width=400&text=Canaves+Oia', 4.9, 580.00, 720.00, 'Boutique', '{"Infinity Pool", "Spa", "Fine Dining", "Concierge"}', '{"Caldera View", "Sunset Views", "Traditional Architecture"}', true),
('hotel_6', 'Burj Al Arab', 'Dubai, UAE', 'Iconic sail-shaped luxury hotel on its own island.', '/placeholder.svg?height=300&width=400&text=Burj+Al+Arab', 4.8, 1200.00, 1500.00, 'Luxury', '{"Private Beach", "Helicopter Pad", "Butler Service", "Multiple Restaurants"}', '{"Iconic Architecture", "All-Suite Accommodation", "Ultra-Luxury"}', true)
ON CONFLICT (id) DO NOTHING;
